services:
  db-projetos:
    image: mysql:8.0
    container_name: db-projetos
    environment:
      MYSQL_DATABASE: db_kernelpanic
      MYSQL_ROOT_PASSWORD: senha
    ports:
      - "3038:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  api-projetos:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-api-container
    ports:
      - "8082:8082"
    depends_on:
      db-projetos:
        condition: service_healthy
    volumes:
      - ./projeto-service:/app/projeto-service
      - ~/.m2:/root/.m2
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-projetos:3306/db_kernelpanic?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=senha