spring.application.name=projeto
server.port=8082

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# Mantenha o padrão, mas deixe o Docker decidir o valor real
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:create}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Insert
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Configurações de conexão (Injetadas pelo Docker)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver